### ISSUE TITLE
Generators & Async Function introduction

### ISSUE THREAD

**Issue by ifraixedes** [BarcelonaJS/speakers#1]
---
level: advanced
language: en
twitter: ifraixedes
tags:
  - JS2016
  - ES7
  - BabelJS
  - JS2015
  - ES6

---

An introductory talk about `async function` the new feature proposed for JS2016 (a.k.a ES7).
I will follow the next sequence:

* Introduction to `function generators` (a few sentences, but mostly code examples)
* Introduction of async function (a few sentence, but mostly code examples)
* How to create a wrapper function which allows to use `function generators` as `async functions` to show that `async functions` are basically syntax sugar.
* To end, I will show an example (simple by more practical than the others) of using an async function to retrieve the list of the files in a folder with `.js` extension

**Comment by eth0lo** [comment]
will you also include how to use generators to get the same result?

**Comment by ifraixedes** [comment]
@eth0lo I was thinking to show an example in how to use a generator to produce the same effect; if you mentioned then it seems that I should do :smile:

**Comment by eth0lo** [comment]
actually async/await is just sugar for generators/promises

**Comment by eth0lo** [comment]
you can check [co](https://github.com/tj/co) for inspiration they do exactly that

**Comment by ifraixedes** [comment]
@eth0lo yes I knew it. I inspected [co](https://github.com/tj/co) implementation more than a year ago when first alpha versions of [koa](https://github.com/koajs/koa) appeared

**Comment by ifraixedes** [comment]
btw, personal opinion, I'm not a big fan of all the things that JS2015/JS2016 brings, JS has lost simplicity.

**Comment by ifraixedes** [comment]
@eth0lo I can adapt this talk to the preferences of the audience, however I need to know at least a week before the day; ideas of what to tell and show are welcome.

**Comment by fmvilas** [comment]
I like it. I've used ```co```, didn't have a look to async/await yet so i guess it can be a nice talk for me. However it may be useful to introduce generators and ```co``` before for people that still don't know about it.

**Comment by ifraixedes** [comment]
@fmvilas it's OK, async function aren't a so large thing to talk; I was thinking to write a short use case in live but if it's better to have an introduction to generators I'll do it; about `co` I can mention it and explain how internally works.

**Comment by fmvilas** [comment]
Thanks man! :clap: :+1:

**Comment by eth0lo** [comment]
``co`` is async/await, that means if you want to use async/await today use co then change the ``*`` from the function definition and the ``yield`` for ``wait``, the easiest migration path ever!

That's why I think is important to talk about generators -> co -> async/await

**Comment by ifraixedes** [comment]
@eth0lo yeah that was a good idea; I was going to use async functions directly with babel, but before that I will introduce generators how to use generators as async functions.

Your idea of the migrations is pretty good, so I will add it to the talk

**Comment by ifraixedes** [comment]
I've updated the title and description now that I have the structure that I'll follow.
