### ISSUE TITLE
Automating Meetups with GitHub

### ISSUE THREAD

**Issue by PatrickHeneise** [BarcelonaJS/speakers#10]
---

level: advanced
language: en
twitter: PatrickHeneise
tags:
- gitevents
- nodejs

---

During the last year, people from BarcelonaJS, NodeBCN and the London Node User Group (LNUG) have developed a service to help event organisers to automate events by distributing information across services. As we all love GitHub, we're using GitHub issues as main tool to plan events. Event and talk information is then distributed to meetup.com, ti.to and other services to create and update events, ticketing, automated website deployment etc.

In this talk I will introduce the concept of Gitevents, how things work and how we approached the problem.

**Comment by eduponte** [comment]
+1

**Comment by motanelu** [comment]
👍

**Comment by Gpx** [comment]
Sorry for not paying attention to this issue, there have been some changes in BarcelonaJS and we're trying to become more reactive. If you still want to give this or any other talk please feel free to contact us.

In the meantime, I'm closing this issue.
