### ISSUE TITLE
Deep Dive into Redux Performance Optimizations

### ISSUE THREAD

**Issue by somebody32** [BarcelonaJS/speakers#11]
---
level: advanced | expert
language: en
twitter: @somebody32
tags:

-   react
-   redux
-   performance

---

Redux + React allow you to write applications and rarely think about performance: everything is fast out of the box. But what to do if you need to scale your app to handle and display 10x more data? Then you can see perf problems even with React.

In this talk, I will show what react-redux does under the hood to make your app fast and what techniques you should avoid to keep it in that state even with 10x data grow.

**Comment by karlas** [comment]
Interested :)

**Comment by giuband** [comment]
+1

**Comment by nye** [comment]
+1

**Comment by lcrespom** [comment]
+1

**Comment by dmitry-zaets** [comment]
+1

**Comment by XescuGC** [comment]
+1

**Comment by onedesert** [comment]
:+1:

**Comment by Morantron** [comment]
:+1:

**Comment by giuband** [comment]
A workshop regarding optimization techniques with Redux would be awesome (also following the great talk by Jorge yesterday)

**Comment by MarcTorrent** [comment]
+1

**Comment by dgil** [comment]
Hi @somebody32! Are you interested in presenting this talk in the May meetup?

**Comment by somebody32** [comment]
Yes, @dgil, can do that

**Comment by dgil** [comment]
@somebody32 Great! You'll be one of the speakers of May 11th meetup :smile:

**Comment by landabaso** [comment]
+1

**Comment by somebody32** [comment]
Sorry, forgot to post the keynote here: somebody32.github.io/high-performance-redux/

On the code slides you need to press up/down to go through
