### ISSUE TITLE
p2p JS 

### ISSUE THREAD

**Issue by Snesi** [BarcelonaJS/speakers#12]
---

level: beginner
language: en
twitter: @davidgshannon
tags:
- webRTC
- multi device presentations

---
### What is WebRTC and how it works from a Frontend Developer's point of view

I gave an introductory talk at work about webRTC and how it can be used for realtime stuff. [https://rtc1.epicdavid.com](https://rtc1.epicdavid.com)

The idea is to showcase what webRTC can do through the presentation itself, making it multidevice and as interactive as possible. 

It's incredible how nowadays a normal FrontEnd Developer can develop a skype clone in less than 100 lines of code.

In this talk I'd talk about:
- webRTC API
- Signaling
- What is a Stun server and a Turn server?
- webRTC Process
- Demos and applications

**Comment by mparramont** [comment]
:+1:

**Comment by Vistur** [comment]
+1

**Comment by aserrabl** [comment]
+1

**Comment by dondanidang** [comment]
+1

**Comment by GinesOrtiz** [comment]
+1

**Comment by carlesnunez** [comment]
+1

**Comment by sluceno** [comment]
+1

**Comment by AdriaRios** [comment]
+1

**Comment by dondanidang** [comment]
+1

**Comment by PatrickHeneise** [comment]
@Snesi our next event is September 22nd. Would you be able to give the talk?

**Comment by Gpx** [comment]
Sorry for not paying attention to this issue, there have been some changes in BarcelonaJS and we're trying to become more reactive. If you still want to give this or any other talk please feel free to contact us.

In the meantime, I'm closing this issue.
