### ISSUE TITLE
Elm - Rethinking UI

### ISSUE THREAD

**Issue by Snesi** [BarcelonaJS/speakers#13]
---
level: beginner
language: en
twitter: @davidgshannon
tags:

  - Elm
  - Functional Reactive Programming

---

### Why Elm?

Elm is slowly becoming a lot of people's favourite language and this talk will show you why. 
Created by Evan Czaplicki as his thesis, the language tries to solve the problem of maintainability of JS code by reimagining how we code UI. 

Elm is a purely functional programming language inspired by languages like Haskell that compiles into JS, HTML and CSS.

This talk will show everyone how Elm can improve your ui coding by avoiding state, blowing your mind and making you a better programmer in general.

**Comment by lcrespom** [comment]
+1

**Comment by somebody32** [comment]
:+1:

**Comment by marduke182** [comment]
+1

**Comment by giuband** [comment]
+1

**Comment by jotabono** [comment]
:+1:

**Comment by tomacco** [comment]
+1

**Comment by marduke182** [comment]
This talk would be an excellent complement / follow-up to the upcoming redux talks ( #8 #9 #11)

**Comment by Snesi** [comment]
@marduke182 +1 :smile:

**Comment by Vistur** [comment]
+1

**Comment by dgil** [comment]
Hi @Snesi. Can you give this talk in the next meetup (May 11th)?

**Comment by Snesi** [comment]
Yeah! I'd love to :).

**Comment by dgil** [comment]
Excellent!!

**Comment by paulopez78** [comment]
+ 1000

**Comment by txels** [comment]
+1
