### ISSUE TITLE
Loving Gulp

### ISSUE THREAD

**Issue by adrilort** [BarcelonaJS/speakers#14]
---

level: beginner
language: en
twitter: adrilort
tags:
- nodejs
- gulp

---

Gulp has overpassed Grunt and is now the most downloaded task runner for NodeJS. Even if it describes itself as "The streaming build system".

In this talk I will explain best practices to organize the tasks and configurations and how to integrate it with node scripts to perform many tasks and group of tasks like
- Transpile TS
- Prepare to deploy
- Projects cleanup
- Execute the project

**Comment by dgil** [comment]
Thank you for your proposal!

**Comment by adrilort** [comment]
thank you @dgil ^_^

**Comment by GinesOrtiz** [comment]
+1

**Comment by fmanuelgonzalez** [comment]
+1

**Comment by pchiwan** [comment]
+1

**Comment by Gpx** [comment]
Sorry for not paying attention to this issue, there have been some changes in BarcelonaJS and we're trying to become more reactive. If you still want to give this or any other talk please feel free to contact us.

In the meantime, I'm closing this issue.
