### ISSUE TITLE
Tumult Hype: the new way of responsive design

### ISSUE THREAD

**Issue by 360fun** [BarcelonaJS/speakers#15]
---
level: advanced
language: en
twitter: 360fun_net
tags:
  - tumult hype
  - html5
  - css3
  - js
  - responsive design
  - crossbrowser
  - wysiwyg

---

We all love Twitter Bootstrap, it's a great tool to make responsive design easily and cross-browser. Sadly too many followed the same approach and the web nowadays looks all the same. The departure of Adobe Flash created a gap into the creativity of web designers and I think that now is time to fill it with a proper alternative: a WYSIWYG editor to build automatically complex HTML5 code. I found in Tumult Hype the best tool out there to start this change right now and I would like to share my experience with you! :)

![b791b60a19ac74ec4905177057af1802c10ea4fb](https://cloud.githubusercontent.com/assets/844090/14508485/ec5a67aa-01c7-11e6-9006-7a9adb06594e.gif)

Francesco Marino ● www.360FUN.net

**Comment by dgil** [comment]
Hi @360fun, do you want to give your talk in the June 22nd meetup?

**Comment by 360fun** [comment]
Sure! :D Let me know all the guidelines please! ^_^

**Comment by dgil** [comment]
@360fun Great! You can check out the `readme` of this repository for general guidelines. 

If you have any doubt you can reply here or contact us on [our slack](http://barcelonajs.herokuapp.com/) or on Twitter [BcnJS](https://twitter.com/BcnJS).

See you at BarcelonaJS meetup!

**Comment by 360fun** [comment]
Is it possible to have the video? It was not posted on YouTube...
