### ISSUE TITLE
Build and manage a Serverless API in JS

### ISSUE THREAD

**Issue by picsoung** [BarcelonaJS/speakers#16]
level: beginner
language: en
twitter: picsoung
tags:
 * serverless
 * APIs
 * AWS Lambda

There is currently a major shift sweeping over the software industry. We went from monolithic apps, to API-driven apps, and now software engineers are breaking their apps into "micro-services".
Managing and connecting those different micro-services could be a hassle for DevOps.
AWS offers an interesting service with Lambda that let you create microservices easily for a very cheap price. With the recent announcement of the API gateway, it lets you create a 100% serverless microservice-based infrastructure for your API and app.

To simplify the creation and the maintenance of a such infrastructure, the community have came up with a framework: Serverless (previously: JAWS)
In this talk we will cover serverless principles using AWS Lambda and Serverless framework to build APIs.

**Comment by dgil** [comment]
Thank you for your proposal! May is already booked, so when will you able to present this talk?

**Comment by picsoung** [comment]
thanks @dgil :)

June could be an option too, did you decide on a date already?

**Comment by dgil** [comment]
Yes, it'll be on June 8th. I'll ping you back when we organize the June meetup to see if you are available 😉

**Comment by PatrickHeneise** [comment]
@picsoung want to move this instead to NodeJS Barcelona?

**Comment by picsoung** [comment]
If you think it's more appropriate.

On Fri, May 13, 2016 at 5:14 PM, Patrick Heneise <notifications@github.com>
wrote:

> @picsoung <https://github.com/picsoung> want to move this instead to
> NodeJS Barcelona?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/BarcelonaJS/speakers/issues/16#issuecomment-219073142>
>



-- 
Nicolas Grenié - Hacker in residence
3SCALE | Out-of-the-Box API Management Platform
Tel: +1 415 351 9635
Web: http://nicolasgrenie.com
Twitter: @picsoung <http://twitter.com/picsoung>
Github: picsoung <http://github.io/picsoung>

**Comment by PatrickHeneise** [comment]
Well, let's have some nodejs at BarcelonaJS ;)

**Comment by dgil** [comment]
Hi @picsoung. Can you give this talk in the next meetup (June 22nd)?

**Comment by picsoung** [comment]
yes sure! :)

On Mon, May 23, 2016 at 4:21 PM, Gil Casadevall <notifications@github.com>
wrote:

> Hi @picsoung <https://github.com/picsoung>. Can you give this talk in the
> next meetup (June 22nd)?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/BarcelonaJS/speakers/issues/16#issuecomment-220994195>
>



-- 
Nicolas Grenié - Hacker in residence
3SCALE | Out-of-the-Box API Management Platform
Tel: +1 415 351 9635
Web: http://nicolasgrenie.com
Twitter: @picsoung <http://twitter.com/picsoung>
Github: picsoung <http://github.io/picsoung>

**Comment by dgil** [comment]
Great!

**Comment by PatrickHeneise** [comment]
@dgil please create an Event first, then label the issue as a talk.

**Comment by PatrickHeneise** [comment]
Sorry about that, bot seems to be down ;(
