### ISSUE TITLE
Polymer Native - build native applications with HTML/CSS/JS with less hassle, boilerplate and no specific knowledge needed

### ISSUE THREAD

**Issue by PixelsCommander** [BarcelonaJS/speakers#17]
---

level: advanced
language: en
twitter: PixelsCommander
tags:
- web components
- ios
- android
- native
- performance
- react native
- polymer

---

Want to have a power of React Native being framework - agnostic? Here you go. Feel free to use HTML/CSS which you know so good to develop completely native applications for mobile platforms.

Currently mobile devices are powerful enough to run mobile web applications at 60 FPS however controls behavior (buttons, sliders, form elements) is different between web and native platforms. Experienced user notice this difference immediately which results in lower user satisfaction for web based apps because they got used to consistent UI behavior on mobile platform of their choice. Creating native facades for web components results in better user experience without additional effort or knowledge needed.

**Comment by PatrickHeneise** [comment]
Could you give this talk in June?

**Comment by PixelsCommander** [comment]
Unfortunately no. Can make it in August / early September.

**Comment by PatrickHeneise** [comment]
We're working on that actually. August we usually have a break, September would probably work.

**Comment by PatrickHeneise** [comment]
@PixelsCommander our next event is September 22nd. Will you be in Barcelona / could you give the talk?

**Comment by Gpx** [comment]
Sorry for not paying attention to this issue, there have been some changes in BarcelonaJS and we're trying to become more reactive. If you still want to give this or any other talk please feel free to contact us.

In the meantime, I'm closing this issue.
