### ISSUE TITLE
Apollo - a practical introduction to GraphQL

### ISSUE THREAD

**Issue by schickling** [BarcelonaJS/speakers#19]
---
language: en
twitter: @_schickling
website: [graph.cool](https://graph.cool)
tags:
  - GraphQL
  - Apollo
  - React

---

![logo-1](https://cloud.githubusercontent.com/assets/1567498/15590364/9fe75a30-2397-11e6-920e-11f1dcf7d6fc.png)

Apollo is a new powerful GraphQL client for your React apps. It combines the best features of other GraphQL clients like Relay and Lokka making it very flexible and simple to use. In this talk we will see how easy it is to get started with GraphQL and Apollo by live coding an example application. We will discuss best practises and get a better understanding for a workflow with GraphQL.

**Comment by dgil** [comment]
Hi @schickling, thanks for your proposal. We already have booked the two talks for June. Patrick has mentioned that you are available only for the June meetup, is that right? If so, maybe you could present a smaller version of this talk in a flash talk?

**Comment by schickling** [comment]
Hi @dgil that should also work! What's the timeframe? 10min?

**Comment by dgil** [comment]
Yes! 10 min will be great 😉  Thank you!

**Comment by PatrickHeneise** [comment]
@PatrickHeneise please create an Event first, then label the issue as a talk.
