### ISSUE TITLE
Sound Synthesis with Web Audio

### ISSUE THREAD

**Issue by lcrespom** [BarcelonaJS/speakers#2]
---
level: interesting for beginners and experts
language: English or Spanish, depending on the audience preference
twitter: lcrespom
tags:
  - WebAudio
  - SoundSynthesis
  - HTML5

---

Computers have always been a great tool for creating music. Until recently, the web platform was limited to playing back recorded sounds, but the Web Audio API provides very powerful and versatile sound synthesis capabilities.

In this talk I will give an introduction to computer sound synthesis, present the Web Audio API, perform some live coding, and demo a complete graphical synthesizer created with Web Audio.

**Comment by eth0lo** [comment]
:+1:

**Comment by fmvilas** [comment]
:+1:

**Comment by PatrickHeneise** [comment]
@lcrespom you're up in January!

**Comment by lcrespom** [comment]
Thank you! My presentation is ready and I promise bells and whistles.

Because the talk is about web *audio*, I will need some audio setup so my mac does not only project video but also send audio to the meeting room speakers. Will that be possible? Otherwise I can bring bluetooth speakers.

**Comment by PatrickHeneise** [comment]
There's an audio jack of course.

**Comment by lcrespom** [comment]
Great!
