### ISSUE TITLE
Building Complex SPAs with React and ESP

### ISSUE THREAD

**Issue by KeithWoods** [BarcelonaJS/speakers#20]
---
language: en 
twitter: keith_woods
tags: 
- esp-js
- state
- react

---

What does it take to build a complex single page application (SPA)? How do you model state in a way that can be reasoned with yet scales with functionality and remains maintainable? How do you separate your view code from your state and update state in a deterministic manor? We'll answer these questions using a real world open source sample application, [Reactive Trader](https://github.com/AdaptiveConsulting/ReactiveTraderCloud), build on [React](https://facebook.github.io/react/) and Evented State Processor ([esp-js](https://github.com/esp/esp-js)).

**Comment by dgil** [comment]
Thanks for your proposal! We have all the spots covered for June's meetup, so I'll go back to you when we have a free spot in the next meetups.

**Comment by KeithWoods** [comment]
Hi ya. Any update on the next meetup slots?

I recently gave this talk at the London Node users group to about 100 people. It seemed well received and I got some great feedback. I'd like to do the same for your usergroup if possible.

**Comment by PatrickHeneise** [comment]
@dgil ?

**Comment by dgil** [comment]
Hi @KeithWoods! If you can make it for the next meetup (July 13th) it'd be great!

**Comment by KeithWoods** [comment]
@dgil yes that'd be great. I'll make plans on my end and be there for the 13th July. Please confirm.

**Comment by dgil** [comment]
@KeithWoods Excellent! Confirmed 😄

**Comment by KeithWoods** [comment]
@dgil  Fantastic. See you on the 13th :)
