### ISSUE TITLE
Server-Side Web Components

### ISSUE THREAD

**Issue by pimterry** [BarcelonaJS/speakers#21]
---

language: en
twitter: pimterry
tags:
- server-side rendering
- web components
- node

---

Web components are changing the fundamentals of web development. They're a powerful new set of APIs that take the core encapsulation and composition magic of modern JS frameworks, and make it a first-class built-in feature of the web.

That's exciting, but we can do even better. Web components are just as powerful an abstraction when rendering UIs server-side, and in that more controlled environment you can lose all the compatibility concerns, and gain powerful new benefits too. Let's take a look at [Server Components](https://github.com/pimterry/server-components): a server-side web components implementation that you can use to clarify your UI, composing the web from powerful standalone components, without the complexity and pain of client-side frameworks.

**Comment by pimterry** [comment]
Ping ping. Any enthusiasm for this?

I've got it booked in at a conference in December, and I'd love give BarcelonaJS a first look sometime beforehand :smile:. Any meetup slots in the next few months would be great.

**Comment by PatrickHeneise** [comment]
@dgil

**Comment by dgil** [comment]
Hi @pimterry, sorry for the delay. Would you be able to present it in the next meetup, July 13th? Otherwise, the next one will be on September if that suits you better. Let me know!

**Comment by pimterry** [comment]
Yes, so soon in July is tricky, and September much easier. Do you have a date for September yet?

**Comment by dgil** [comment]
Ok, I'll ping you back when we have a date 😄

**Comment by PatrickHeneise** [comment]
@pimterry the date would be September 22nd. Would you be able to give the talk then?

**Comment by pimterry** [comment]
No, sorry, since we last talked about this I've now completely booked up my September. I'm also not free for the 20th of October, which I assume would be the next date?

I could do the 17th of November though, or the 27th of October instead, if either of those are useful to you.

**Comment by PatrickHeneise** [comment]
The dates aren't confirmed yet unfortunately. But we'll let you know as soon as we have them. Thanks!

**Comment by Gpx** [comment]
Sorry for not paying attention to this issue, there have been some changes in BarcelonaJS and we're trying to become more reactive. If you still want to give this or any other talk please feel free to contact us.

In the meantime, I'm closing this issue.
