### ISSUE TITLE
Recording Audio/Video streams in the browser with MediaRecorder 

### ISSUE THREAD

**Issue by sajirdalas** [BarcelonaJS/speakers#22]
---
language: en
Level: beginner/medium
twitter: SajirKun
tags:
  - web API
  - Mozilla

---

Mozilla, Google and other browser makers are hard at work standardizing new Web APIs that will extend the abilities of the web. One such API is the [MediaRecorder](url) which will allow Javascript to very easily record media streams such as video or audio from different sources and save them or potentially manipulate them using other web APIs.

On this talk I will explain the current version of the MediaRecorder and provide examples of code snippets that can be used to capture and encode audio and video from the browser. Depending on the time constrains it might also be possible to include pointers for manipulating the data from the streams using something like Web Audio API.

I will give this talk as a Mozilla volunteer in the Tech Speakers program.

**Comment by PatrickHeneise** [comment]
Hi @sajirdalas, that sounds cool. When would you be able to give this talk?

**Comment by sajirdalas** [comment]
Next meetup is on the 13 of July, correct? I could have it ready for that or the next one.

**Comment by PatrickHeneise** [comment]
That would be cool!

**Comment by sajirdalas** [comment]
hi @PatrickHeneise, any confirmation on the July meetup? I ask just to make sure to set my work schedule with enough time to finish the presentation.

**Comment by dgil** [comment]
Hi @sajirdalas, sorry for the delay. Are you able to present on the July 13th meet up?

**Comment by sajirdalas** [comment]
Yes. I will get the presentation done on the weekend. How long (in time) do presentations usually aim for?

**Comment by dgil** [comment]
@sajirdalas Excellent! You have 25 minutes for the presentation and then there is 5 minutes for questions. See you on July 13th! 😄
