### ISSUE TITLE
Adding 3D to your Website with the Autodesk Forge Viewer

### ISSUE THREAD

**Issue by leefsmp** [BarcelonaJS/speakers#23]
---

language: en 
twitter: https://twitter.com/F3lipek
tags:
- WebGL
- Three.js
- Node 

---

Philippe Leefsma, developer-evangelist at Autodesk will take you through a demo of the Autodesk Viewer capabilities, a WebGL-based technology that enables your website users to visualize and interact with stunning high-fidelity 3D & 2D models in a browser or on a mobile device. We will present some of our coolest JavaScript samples to illustrates integration possibilities between the Viewer API and popular frontend frameworks and libraries such as Angular.js, React, Snap.svg, D3 ...

**Comment by Gpx** [comment]
Sorry for not paying attention to this issue, there have been some changes in BarcelonaJS and we're trying to become more reactive. If you still want to give this or any other talk please feel free to contact us.

In the meantime, I'm closing this issue.
