### ISSUE TITLE
Boost your Web Application with C++!  

### ISSUE THREAD

**Issue by leefsmp** [BarcelonaJS/speakers#25]
---

language: en 
twitter: https://twitter.com/F3lipek
tags:
- JavaScript
- ams.js
- Web Assembly

---

Whether you are a hardcore C++ developer, a JavaScript fan or a Web enthusiast, come to see how you can get started compiling C++ to run in browsers and get a sneak peak at the future of web development!

Following a quick introduction to Emscripten, asm.js and Web Assembly, I will show you how you get set up to compile your first C++ code into JavaScript, I will also talk about my own experience at implementing a 3D particle system in JS and C++, then converting it to asm.js and Web Assembly to see what it takes and how much faster it can run in the browser based on concrete [performance metrics](https://github.com/leefsmp/Particle-System) I implemented ...

Cheers!

**Comment by Gpx** [comment]
Sorry for not paying attention to this issue, there have been some changes in BarcelonaJS and we're trying to become more reactive. If you still want to give this or any other talk please feel free to contact us.

In the meantime, I'm closing this issue.
