### ISSUE TITLE
Crossbrowser testing with Nightwatch, Travis and Saucelabs

### ISSUE THREAD

**Issue by motanelu** [BarcelonaJS/speakers#26]
---
language: en 
twitter: @motanelu
tags:
  - testing
  - nightwatch
  - travis
  - saucelabs
---
Sooner or later, any application needs to be released. And before that, it needs to be tested. Ideally!

The purpose of this talk is to explore Nightwatch as a testing framework, how to set up an automated CI system using Travis and using SauceLabs as a browser farm.

**Comment by carlesnunez** [comment]
Will be so useful hear that talk

**Comment by masylum** [comment]
Awesome! March is already full (unless someone dumps us) but we can schedule for April 💪

**Comment by motanelu** [comment]
That'd be awesome! I'm going to start preparing the presentation then

**Comment by Gpx** [comment]
Closing this issue since we're going to have the talk in this month's meetup.
