### ISSUE TITLE
Building a performant, in-browser code editor

### ISSUE THREAD

**Issue by stagas** [BarcelonaJS/speakers#27]
---
language: en
twitter: stagas
tags:
  - algorithms
  - data structures
  - benchmarking
  - vanilla js
---
How NIH syndrome contributes to a performant code editor that runs on all devices.

Walkthrough of the makings, overgoing limitations and pushing performance to the edge.

**Comment by masylum** [comment]
Awesome!

**Comment by Gpx** [comment]
Closing this issue since we're going to have the talk in this month's meetup.
