### ISSUE TITLE
Hardware Hacking for JavaScript Developers

### ISSUE THREAD

**Issue by pimterry** [BarcelonaJS/speakers#28]
---

language: en
twitter: pimterry
tags:
  - node
  - hardware
  - arduino
  - raspberry pi
  - resin.io

---

Better with react than resistors? Understand single-page apps, but lost with a single-board computer? JavaScript is great, but sometimes you want to take your skills out into the real world.

In this talk we'll connect your JavaScript to some hardware, and learn how to interact with and control everything from individual sensors, to microcontroller boards, to whole fleets of raspberry pi's.

---

Discussed on Twitter earlier today. Note that this is a fairly big talk - I'll need a 40 minute slot.

**Comment by carlesnunez** [comment]
+1000

**Comment by Gpx** [comment]
Hey, @pimterry I'm the one you talked to today. The proposal looks great. We'll try to let you know the possible dates as soon as we know them.

Thank you!

/cc @masylum

**Comment by pimterry** [comment]
Do we have dates for this yet?

Also, this talk would fit really nicely into the same night as https://github.com/BarcelonaJS/speakers/issues/29, if that's doable. Note that this talk needs 40 minutes though, and I'm not sure how much time that other talk would need or how much time you have overall, so it might be a squeeze.
