### ISSUE TITLE
Web Bluetooth & Lego Robots

### ISSUE THREAD

**Issue by 360fun** [BarcelonaJS/speakers#29]
---
level: advanced
language: en | es
twitter: 360fun_net
tags:
  - web_bluetooth
  - tumult_hype
  - html5
  - lego
  - sbrick
  - robots
---

I think it's time to talk about the new Web Bluetooth APIs and the Physical Web! :D

The speech will be about:
- [Bluetooth.js](https://github.com/360fun/bluetooth.js) a small library to make easier the approach to Web Bluetooth
- [SBrick.js](https://github.com/360fun/sbrick.js) a library that allows to communicate with a Lego compatible Bluetooth controller ([SBrick](https://www.sbrick.com/))
- [SBrick Web Controller](https://360fun.github.io/SBrick-Web-Controller/) a web remote controller for Lego robots built using Tumult Hype and the previous libraries

![Lego Robot](https://mir-s3-cdn-cf.behance.net/project_modules/max_3840/89239045242975.58d974efb2188.jpg)

Here is the official page of the project: [sbrick.360fun.net](http://sbrick.360fun.net/)

Enjoy! ^_^v

**Comment by Gpx** [comment]
Very nice, when could you give this talk?

**Comment by 360fun** [comment]
In May probably! :)

**Comment by Gpx** [comment]
@360fun would you be able to give the talk in June? We were thinking to pair you up with #28

**Comment by 360fun** [comment]
Sure, I think it's a really good idea! ;)

**Comment by Gpx** [comment]
Hey @360fun would the 15th of June work for you?

**Comment by 360fun** [comment]
Sounds good to me! :)

**Comment by 360fun** [comment]
News about the time of the speech? Thanks!

**Comment by Gpx** [comment]
Hi @360fun the time should be from 7pm. I'll confirm tomorrow

**Comment by Gpx** [comment]
Hey, @360fun, in the end, the day will be the 19th, we're starting at 6.45. Is it ok for you?

**Comment by 360fun** [comment]
Perfect, thank you! :)

**Comment by Gpx** [comment]
@360fun can you please provide a small bio? Just a couple of sentences are enough

**Comment by 360fun** [comment]
In this speech I will talk about **Web Bluetooth** and my project about making **robotic easy for everyone**, in order to use it for: **Fun**, **Education**, **Art**, **Domotics** and much more!
I will show you how to use the latest web technologies (HTML5, CSS3, JavaScript/ECMAScript 6) and tools (Chrome, Tumult Hype, FireBase...) to control Lego robots through **SBrick** (a Lego compatibile Bluetooth controller) and my **OpenSource** library [SBrick.js](https://360fun.github.io/sbrick.js/).

Official project page: [sbrick.360fun.net](http://sbrick.360fun.net)

**Comment by 360fun** [comment]
My name is Francesco Marino ([360FUN.net](http://www.360fun.net)) and I define myself as "360°CREATIVE": I've a wide background in Web Dev, UI-UX Design and Multimedia but I also like to investigate other kind of disciplines.
In this speech I will talk about **Web Bluetooth** and my project about making **robotics easy for everyone**, in order to use it for: **Fun**, **Education**, **Art**, **Domotics** and much more!
I will show you how to use the latest web technologies (HTML5, CSS3, JavaScript/ECMAScript 6) and tools (Chrome, Tumult Hype, FireBase...) to control Lego robots through **SBrick** (a Lego compatibile Bluetooth controller) and my **OpenSource** library [SBrick.js](https://360fun.github.io/sbrick.js/) with and without programming.

Official project page: [sbrick.360fun.net](http://sbrick.360fun.net)
