### ISSUE TITLE
Hermes - Asynchronous Microservices right to your frontend

### ISSUE THREAD

**Issue by fmvilas** [BarcelonaJS/speakers#3]
---
level: advanced
language: english or spanish, depending on audience
twitter: @fmvilas
tags:
  - asynchronous
  - microservices
  - amqp
  - rabbitmq
  - websockets
  - frontend
  - react

---

I want to talk about Hermes. This is an in-progress concept on how [asynchronous microservices architecture (based on message brokers, such as RabbitMQ)](http://www.slideshare.net/bpedro/asynchronous-microservices-in-nodejs) could also be used in frontend. The fact of using Node.js for microservices allow us to share code with frontend, but a new concept is being investigated about *sharing infrastructure*. At a glance, you could see you can do a backend without a REST API, event-based (instead of request-based) and a [backend for frontend](http://samnewman.io/patterns/architectural/bff/) approach. Curious about it? Join us to learn and discuss about it.

**Comment by eth0lo** [comment]
have you seen [postal](https://github.com/postaljs/postal.js)? they also have a plugin for rabbitmq transports

**Comment by fmvilas** [comment]
@eth0lo yes, i know it. It was inspired by AMQP however it differs a lot. I was thinking in a client (not just browser) implementation of exchanges, queues, messages, consumers, etc. And also explain how to integrate it with React for instance.

Implemetation details aside, i would like to explain and debate the architecture.

**Comment by ifraixedes** [comment]
@fmvilas which month are you available to give the talk?

**Comment by fmvilas** [comment]
I guess in March because in February i'm going to be very busy due to the MWC.

**Comment by PatrickHeneise** [comment]
March 15 works?

**Comment by fmvilas** [comment]
Ok let's do it!

**Comment by PatrickHeneise** [comment]
yeah!
