### ISSUE TITLE
Back to the 80s with Voice Services

### ISSUE THREAD

**Issue by acalpixca** [BarcelonaJS/speakers#30]
---
language: en | es 
twitter: lavigi
tags:
  - VoiceServices
  - AmazonEcho
  - Alexa
  - AWSLambda
  - node

---
Learn the key concepts about Voice Services, take a ride on the DeLorean to check that voice user interfaces are fairly similar to the simpler, linear, deterministic user interfaces from the 80's, and learn to create a Voice Application with Amazon Alexa, Lambda Functions and node.js.

Content:

- Introduction.
- Solving the Puzzle: Building Blocks in a Voice Services
- application.
- Alexa Skills.
- LEX Chatbots.

I gave this talk at [Barcelona Nodeconf 2017](http://barcelona.nodeconf.com) just last week.  It took 30 minutes. On this occasion I would like to extend it to 45 minutes so that we can see the structure of a AWS Lambda function with node.js that leverages the alexa-sdk package, and also include a demo, either with the echosim.io emulator or with an Amazon Echo device.

**Comment by Gpx** [comment]
Hi @acalpixca, could you give this talk in May?

**Comment by acalpixca** [comment]
Hello @Gpx ! 
Well, it will depend on the date :-) But if I am in Barcelona, then surely yes.
So, when would it be?
Thanks!

**Comment by Gpx** [comment]
@acalpixca we'll let you know the date as soon as we know it

**Comment by acalpixca** [comment]
Thanks! In May, during weekdays in the evening I am free every day except the 8th and the 22nd. Hope it works out!

**Comment by Gpx** [comment]
@acalpixca, is May 30 ok for you?
