### ISSUE TITLE
Puppets: HTML5 for new human-computer interfaces

### ISSUE THREAD

**Issue by AquiGorka** [BarcelonaJS/speakers#31]
---
language: en | es
twitter: AquiGorka
tags:
  - js + webrtc + smartphone + webgl
  - https://github.com/AquiGorka/puppets

---
The talk will go thorugh the work + code I developed to create the 3D virtual Puppet remote controlled via a smartphone:

A puppet consisting of 10 body elements (head, torso, shoulders, arms, thighs and legs) and the proper joints (to connect the body elements and the control bar) gets rendered in the browser via WebGL (using ThreeJS).

To achieve realism it applies a physics engine (oimo.js). Every time the puppet gets rendered the physics thread calculates where each element is positioned as well as the element's orientation.

In order to remote control the puppet a WebRTC bridge is used (Peer.js helps the two clients find each other).

Once the connection is established the smartphone's gyroscope sends it's data over and the puppet's control bar mimics the smartphone's orientation.

**Comment by Gpx** [comment]
Hey, @AquiGorka thanks for the submission. When could you give the talk?

**Comment by AquiGorka** [comment]
Hello @Gpx, how often do you usually meet? Where? When are the next meetings scheduled?

**Comment by Gpx** [comment]
We usually meet once a month at [MWC](https://www.mobileworldcentre.com/). We don't have a date for our next meetup. Which days would be good for you?

**Comment by AquiGorka** [comment]
@Gpx I currently live in Barcelona so I have full time availability for the next couple of months - I assume the meetups are held after office hours and during the week days right?

With just a heads up notice (about 2 weeks) I can setup the proper slides for the talk.

**Comment by Gpx** [comment]
I will contact you when we know which day we want to organize it. The meetups are at 7.00pm till 9ish during weekdays

**Comment by AquiGorka** [comment]
Awesome.
