### ISSUE TITLE
Building first project with Vue.js

### ISSUE THREAD

**Issue by picsoung** [BarcelonaJS/speakers#32]
---
language: en
twitter: picsoung
tags:
  - vuejs
  - algolia
  - apis
---

Few months ago I have launched my first big project using Vue.js framework. The project received thousands of views. I want to share the story behind this project and technical learnings.

Project: [http://🌚🌞.ws](http://🌚🌞.ws)
Date: dont know if you plan a November meetup, but I will be in BCN from 24to 30th of November, and would love to stop by!

**Comment by Gpx** [comment]
Hi, @picsoung thanks for the proposal. The talk looks very interesting. Currently, I'm trying to find a venue for November. I'll let you know as soon as I have some more info.

**Comment by Gpx** [comment]
Hey, the meetup will be on the 23rd unfortunately—we can't have the venue on other days. How would you like to talk at the React meetup instead?

**Comment by picsoung** [comment]
Arf, too bad, I wont be in Barcelona on time.

It's about Vue... but React meetup seems appropriate too :)

**Comment by Gpx** [comment]
That's what we thought
