### ISSUE TITLE
Resilient Microservice WebAPI with REST and API Gateway

### ISSUE THREAD

**Issue by XVincentX** [BarcelonaJS/speakers#33]
---
language: en
twitter: d3dvincent
tags:
  - api gateway
  - node
  - rest
---

Splitting your application into a bunch of microservices is a non trivial task with a lot of challenges, that might end up in with a complete different system in terms of architecture, components and more importantly the API surface you’re exposing; and that’s breaking the clients.

Can we prevent that somehow?

In this presentation we will start with a sample monolithic application and start to refactor it into a set of microservices using a naive approach, taming all the problems that will rise one by one, discovering how a REST architectural style for the WebAPI as well as an API Gateway are invaluable tools for journey.

At the end of the presentation, we’ll see how we can switch from the monolithic version to the microservices version without breaking the clients at all.

P.S: It's going to be Javascript. Gateway included 😏

**Comment by Gpx** [comment]
Hi, @XVincentX thanks for the proposal. We'already have speakers for November and we were planning something different for December. Would you able to give this talk next year?

**Comment by XVincentX** [comment]
@Gpx 

Seguro. Espero tu noticias entonces!

**Comment by XVincentX** [comment]
@Gpx Hola — hay algunas novedades sobre esto?

**Comment by Gpx** [comment]
We should have a free spot in October, would it work for you?

**Comment by XVincentX** [comment]
I think we can sort this out. Do you have any specific date in mind?

**Comment by Gpx** [comment]
Not at the moment. Do you have any preference?

**Comment by XVincentX** [comment]
I am going to be away in United States the first two weeks, I think we can aim for the third one.

**Comment by Gpx** [comment]
Ok, I'm going to try to see if we can get a venue

**Comment by Gpx** [comment]
How does October 18th look to you?

**Comment by Gpx** [comment]
Ping

**Comment by XVincentX** [comment]
Ops — I completely missed the message. It would be better for me to make it on 22-23 Oct?

**Comment by Gpx** [comment]
We were aiming for the third week of October. I can ask for the 22-23. If those are not available would the 18th work for you?

**Comment by XVincentX** [comment]
I can triple check and give you more info but it's really unlikely. I'll be in US during that period and we haven't booked my return yet.

**Comment by Gpx** [comment]
We booked the place for the 22nd

**Comment by XVincentX** [comment]
Cojonudo!

**Comment by Gpx** [comment]
Hey, we're going to announce the meetup on Monday. Can you send me a short bio, please?

**Comment by Gpx** [comment]
Ping

**Comment by XVincentX** [comment]
Is there anyway we can change the date for this event? 

I’ve been sent in United States by my company and I’ll be back on 17 October in Madrid. I can still make it I might arrive in a horrible condition. If everything has been already set up I’ll be there, I promise. Otherwise, if we could reschedule it during November, that would save my life.

**Comment by Gpx** [comment]
The date is the 22nd. If you arrive on the 17th, you'll have five days to recover. Now is too late to cancel the venue.

**Comment by XVincentX** [comment]
Ha! I thought it was on 18th! My mistake! I'll be there then no problem. Let me land in Seattle and I'll send you my bio!

**Comment by XVincentX** [comment]
```
Vincenzo Chianese is a Software Developer focused on WebAPIs, User Interfaces and Hypermedia enthusiast. He has been working for several API companies helping users to build to build better APIs.

Although his past experiences include Web Services in .NET, Windows Drivers in C++, along with Windows Applications in MFC, he’s now mostly working on NodeJS, in particular on Express Gateway, probably the most popular Open Source API Gateway written in Javascript.

He also enjoys speaking at a number of conferences, where he usually shares the experiences he had during his path.
```

**Comment by Gpx** [comment]
Yep
https://www.meetup.com/BarcelonaJS/events/255193271/

**Comment by Gpx** [comment]
Hi @XVincentX, all good for today? Anything you need?

**Comment by XVincentX** [comment]
I'm at the Madrid airport, departing in 20 minutes :)

Should be all good and ready to go.

**Comment by XVincentX** [comment]
@Gpx Do you have a USB-HDMI convertor? I'm on a MacBook Pro with USB-C port only and I forgot mine.

**Comment by Gpx** [comment]
We have it

**Comment by XVincentX** [comment]
I'm upstairs

**Comment by XVincentX** [comment]
I have a MacBook Pro with Usb C. Please tell me you have an adapter because I forgot I mine.

**Comment by XVincentX** [comment]
Me das tu número de móvil por favor? Por sea caso. Ya estoy de camino por el Movistar centre

**Comment by Gpx** [comment]
Closing this issue. Grazie Vincenzo!
