### ISSUE TITLE
Story of side project

### ISSUE THREAD

**Issue by alvarotrigo** [BarcelonaJS/speakers#34]
---
language: en (but can do Spanish if preferred) 
twitter: imac2
tags:
  - javascript
  - open source
  - side projects 
---
It is a talk about believing in ourselves. A motivational talk about what we can achieve with just enough time and passion for what we do.
A reminder that we do not have to be Mark Zuckerberg or any kind of genius to achieve something we can life from and be happy with.

This is my own story.

4 years ago I created [one of my firsts GitHub repositories](https://github.com/alvarotrigo/fullPage.js) with a jQuery script I started as a side project. 
A few months ago I quit my job and now work full time on the project and things around it.

I am now earning more than with my previous position and the library is within the top 50 most stared and forked Javascript projects of all time in Github.

Used by companies like Google, McDonalds, BBC, EA, and British Airway, it is currently the most popular, used and complete library of its kind. 

I can talk about the process, the things I learned on the way, the way I manage the repository and the issues tracker, emails, how do I make money, why I want to make money and why I believe it improves the quality of the open source project, the way I deal with customers etc.

**Comment by Gpx** [comment]
Hi, @alvarotrigo thanks for proposing a talk. Do you think you could give it in January?

**Comment by somebody32** [comment]
Hey @alvarotrigo, are you still up to give that talk in January? We're preparing the line-up now

**Comment by alvarotrigo** [comment]
Sorry, I didn't respond because I didn't know if I was gonna be busy in January or not. 
This is not the best month for me, I'm gonna be quite busy moving to another city during this month.

I'll close the topic until I find myself in a better situation where I can go to Barcelona and do the talk.
