### ISSUE TITLE
Animate like everybody is dancing - Animations in React

### ISSUE THREAD

**Issue by jepser** [BarcelonaJS/speakers#36]
---

name: Jepser Bernardino
twitter: jepser
github: jepser
title: Animations in React

---

I'm a software engineer from Guatemala. Working @Typeform.

---
From the beginning of internet, animations have being around, from the ancient Markee to inJS solutions, let's explore the current tools what they solve and how they solve it. And dive more on how we solve animations @Typeform when we created a new experimental renderer, [Conversations](https://labs.typeform.com/cui/).

**Comment by carlesnunez** [comment]
I'm very interested in this one! 👍 Could be great if you provide more tech info about it but looks interesting!

**Comment by jepser** [comment]
@carlesnunez hey thanks! which type of tech info are you interested? If you're talking about the libraries, it will be covered in the talk.

**Comment by carlesnunez** [comment]
Yes it was more about the libraries just to check it by myself at home before going to the talk but if you want to talk about them at the talk is ok for me!

Thanks!
