### ISSUE TITLE
How does Redux works under the hood? Let’s implement it from scratch.

### ISSUE THREAD

**Issue by ca057** [BarcelonaJS/speakers#38]
name: Christian Ost
twitter: [_christianost](https://twitter.com/_christianost/)
github: [ca057](https://github.com/ca057)
title: How does Redux works under the hood? Let’s implement it from scratch.

---

I’m a developer building user interfaces at [Typeform](https://typeform.com).

---

Together with React, Redux as a state management solution got extremely popular. Still a lot of people seem to be struggling with it, not understanding the "magic" of Redux. Maybe it is time to stop looking at how to use Redux and instead look under the hood, to understand what is actually happening. As a basic implementation of Redux doesn’t require a lot of lines, let’s implement it from scratch.

After shortly refreshing the principles of Redux, I will live code a basic implementation of Redux (some shortcuts included, as we’re short in time) and use it in a vanilla JS application (yes, Redux can be used without React and implementing react-redux as well will cost just more valuable time :) ).

After the talk, the audience will have an understanding on how the different parts of Redux work together. The talk might be most valuable for developers with less experience in Redux, although others might gain some new insights as well by finally looking under the hood.

**Comment by tpombeiro87** [comment]
Christian is not available to do this talk anymore
