### ISSUE TITLE
Using React Native for cross-platform development

### ISSUE THREAD

**Issue by sharnik** [BarcelonaJS/speakers#4]
---

level: beginner
language: en
twitter: sharnik
tags:
- react
- mobile

---

I'd like to give an introduction on how to get started with developing cross-platform mobile applications (iOS and Android) in React Native. Some knowledge of how React works is useful, but I'd quickly go through the basic components to refresh them. 

I want to focus on answering three questions:
- What is React Native useful for?
- Who is React Native useful for?
- What do I need to learn to launch my first app?

**Comment by ifraixedes** [comment]
@sharnik  which month are you available to give the talk?

**Comment by sharnik** [comment]
March, preferably. We're currently working on an app for a client using React Natie and want to go through all the hoops of putting it in production to be able to also cover that.

**Comment by ifraixedes** [comment]
@sharnik make sense it will be very good to hear about your real experience.
Thanks we'll try to schedule your talk for March.

**Comment by mparramont** [comment]
I vote for this one! :+1:

**Comment by vermiculite** [comment]
I vote for this one!

**Comment by nye** [comment]
+1

**Comment by PatrickHeneise** [comment]
@sharnik does this work for March 15?

**Comment by sharnik** [comment]
Sorry, I won't manage to prepare the talk in time :(
Next month?

**Comment by PatrickHeneise** [comment]
April should work, yes.

**Comment by Vistur** [comment]
+1

**Comment by PatrickHeneise** [comment]
@sharnik you're up for April :)

**Comment by sharnik** [comment]
👌

**Comment by landabaso** [comment]
+1

**Comment by ifraixedes** [comment]
@landabaso this talk was given on April event, the issue isn't close because we're on the way to publish a few things related to the talk

**Comment by landabaso** [comment]
Oups! I see. I got here from the list of submitted talks for [May 11, BarcelonaJS meetup](http://www.meetup.com/BarcelonaJS/events/229637074/). No prob!

**Comment by ifraixedes** [comment]
@landabaso no problem!
