### ISSUE TITLE
Migrating a C# App to JavaScript for a Smarter Locker network

### ISSUE THREAD

**Issue by TomSelva** [BarcelonaJS/speakers#40]
---
name: Tom Selva
email: tomas@mayordomo.io
title: Migrating a C# App to JavaScript for a SMARTER LOCKER Network
---
Tom was the Lead Innovation Engineer for Norman Foster. He's a founder of MOMA award-winning design company Two Islands and London’s fastest growing robotics startup Q-Bot. Currently he is building an open smart locker network.
---
The talk is about how we built a hardware + software solution to create the world's first "free access" locker network, allowing hundreds of providers to connect to a given point of service,  allowing customers to order any service they want, and eliminating vendor lock-in. A system that demands reliability and security, and a different software design perspective.

**Comment by tpombeiro87** [comment]
This talk has happen already
