### ISSUE TITLE
Svelte + D3 = data viz made easy

### ISSUE THREAD

**Issue by glippi** [BarcelonaJS/speakers#44]
name: Gabriele Lippi
twitter: gabrielelippi
github: glippi
title: Svelte + D3 = data viz made easy

Software Craftperson @ Codurance.

Recently I had the chance to build a prototype for a data viz project with Svelte and I'd like to share my experience.

The idea is to have first a quick look on Svelte, what are the differences between it and React/Vue/Angular.

Then I would like to do a simple live coding session, to see in action the points previously touched. 

I'll probably give a data visualization footprint to my talk, so I'll probably scratch the surface of D3 too.

The idea is not to dive deep inside Svelte neither D3, but to see what one can accomplish and in how much time with how much amount of work/code. 
The level of the talk would be for beginners.

**Comment by IagoLast** [comment]
Closed in https://www.meetup.com/es/BarcelonaJS/events/266381262/ 🎉
