### ISSUE TITLE
React Native: Intro to Yoga (Layout and Styling)

### ISSUE THREAD

**Issue by kabaros** [BarcelonaJS/speakers#46]
I am a Full-stack software developer, recently moved to Barcelona for a job with Glovo.

Talk level: beginner
language: en
twitter: kabaros

---

Intro to React Native with emphasis on layout and styling

- Why React Native
- An intro to [Yoga](https://yogalayout.com/) - the layout engine behind React Native. 
   - How to position components
   - RTL
- How to style text: styles' reuse, theming, screen sizes

**Comment by motanelu** [comment]
Hi, we're looking for speakers for October / November. Are you interested in giving a presentation? Can you please reach out at hello@tudorbarbu.ninja? Since you're not following @bcnjs on twitter, we can't DM. Thanks!

**Comment by IagoLast** [comment]
Closed in https://www.meetup.com/es/BarcelonaJS/events/266381262/ 🎉
