### ISSUE TITLE
Micro Frontend Architecture - Building an Extensible UI Platform

### ISSUE THREAD

**Issue by ErikGrijzen** [BarcelonaJS/speakers#48]
At New Relic, we recently released New Relic One, the result of a two-year engineering project to migrate to a micro frontend architecture. This new platform is bringing our users from several separate product-aligned monolithic applications to one single platform and unified experience.

The new UI is broken down into separate micro applications, views, and other extension points. This extensible way of building the platform allows us to reduce the toil required for our development teams to deliver new features. This means we can bring value to our customers much faster and with lower risk.

Not only that, but this new architecture was designed to allow developers from our customers and third parties to extend our platform for their own special use cases. External developers can deploy custom integrations and visualize them using the same UI components and backend services that the core New Relic One platform is built upon.

Based on our real-world experience going through this transition, we will take an honest, open look at the benefits that come with such an architecture, such as ease of deployments, increased team autonomy, localized complexity, and more. There were also many challenges along the way and we will reflect on how we tackled some of the hardest problems we faced - including performance, resiliency, UI consistency, scalability, and even organizational alignment.

**Comment by IagoLast** [comment]
Closed in https://www.meetup.com/es/BarcelonaJS/events/267578342/ 🎉
