### ISSUE TITLE
The frontend developer's workflow

### ISSUE THREAD

**Issue by svenanders** [BarcelonaJS/speakers#5]
---
level: beginner + advanced
language: en 
twitter: svenardocom
tags:
  - tooling
  - webpack
  - optimisation
  - developer_bliss

---

Learn the tools you need to help you stay productive on the front-end.

The talk will walk through and demonstrate modern tooling, config and tricks you can employ to create web apps efficient. It will demonstrate how you can use these tools to avoid doing too much work (and just let the computer do it for you), as well as walking through efficient use of Webpack and advanced optimization.

Note: This talk is appropriate for both beginners and advanced frontend developers.

**Comment by dgil** [comment]
Thank you for your proposal! When would you be able to give this talk?

**Comment by svenanders** [comment]
Anytime :)

**Comment by dgil** [comment]
@svenanders Could you give this talk in the February meet up? It'd be great :smile:

**Comment by svenanders** [comment]
I think it's a good chance that I can :) Is the date set?

**Comment by dgil** [comment]
@svenanders Excellent! Yes, the data is set. It'll be on February 10th.

**Comment by PatrickHeneise** [comment]
@dgil please create an Event first, then label the issue as a talk.

**Comment by dgil** [comment]
@svenanders your talk is now confirmed for the February meetup :smile: :ok_hand:

**Comment by svenanders** [comment]
Fantastic :)
