### ISSUE TITLE
New Relic programmability architectural overview

### ISSUE THREAD

**Issue by mjesun** [BarcelonaJS/speakers#50]
New Relic released a few months ago its programmability feature, allowing third-party users to extend our platform with their own applications, which was made possible thanks to our [revamped frontend architecture](https://github.com/BarcelonaJS/speakers/issues/48). The feature required developing not only changes in our website (one.newrelic.com), but also a CLI to enable setting up the development environment.

During the talk we will perform an introduction to the architectural approach we chose to develop the feature, how we circumvented some technical limitations imposed by browsers to achieve similar effects to what our own engineers can do, and how we make the platform extensible overall while keeping customers' data safe.

**Comment by IagoLast** [comment]
Closed by https://www.meetup.com/es/BarcelonaJS/events/267578342/ 🎉
