### ISSUE TITLE
Internet of things and you

### ISSUE THREAD

**Issue by svenanders** [BarcelonaJS/speakers#6]
---

level: beginner
language: en
twitter: svenardocom
tags:
- iot
- javascript_robotics

---

Internet of things is going to be awesome - you just don't know it yet.

This talk will delve into the exciting world of Internet of things. It will give you a clearer picture of just what it is, how it will affect you, and how you can use JavaScript to make and program your own IOT devices.

**Comment by PatrickHeneise** [comment]
This sounds great! When would you be able to give this talk?

**Comment by svenanders** [comment]
Hi Patrick! Thanks for the vote of confidence :) I was thinking february/march or later, but I'm flexible. I picked up a lot of interesting insight while working at a telecom company this fall/winter (where I'll be working for the rest of january, possibly stretching into into february).

**Comment by AndreuGenestar** [comment]
+ 1

**Comment by eduponte** [comment]
+1

**Comment by PatrickHeneise** [comment]
@svenanders this topic got lost I think. Would you be able to give the talk Sep 22?

**Comment by Gpx** [comment]
Sorry for not paying attention to this issue, there have been some changes in BarcelonaJS and we're trying to become more reactive. If you still want to give this or any other talk please feel free to contact us.

In the meantime, I'm closing this issue.
