### ISSUE TITLE
The Universal Datatype

### ISSUE THREAD

**Issue by sergi** [BarcelonaJS/speakers#7]
---

level: advanced
language: en
twitter: @sergimansilla
tags:
- rxjs
- reactive
- javascript

---

In this talk I'll introduce reactive programming using RxJS and it's central concept: the Observable Sequence. Observable sequences give developers super-powers by letting you manage asynchronous code with ease, and think about complex flows of events as if they were all synchronous, abstracting time in a way you've never seen before. You can think of it as a simpler Promise, but on steroids. I'll show you some cool programs and examples straight from my Reactive Programming book, and if there is time, I might try to even do some live-coding!

**Comment by dgil** [comment]
Thank you for the proposal! When will you able to give it?

**Comment by ifraixedes** [comment]
:+1:

**Comment by sergi** [comment]
@dgil I can do it on the next edition, after March 15th. April, I presume?

**Comment by dgil** [comment]
@sergi Sorry for the delay! The talks for April have already been selected. Are you available for May? :smiley:

**Comment by dgil** [comment]
@sergi Will you be able to present it in the May meetup?

**Comment by sergi** [comment]
Hi @dgil,

Unfortunately I am away most of May. I'd definitely be up for June though!

**Comment by dgil** [comment]
Ok, no problem. I'll ping you again in a month :wink:

**Comment by Gpx** [comment]
Sorry for not paying attention to this issue, there have been some changes in BarcelonaJS and we're trying to become more reactive. If you still want to give this or any other talk please feel free to contact us.

In the meantime, I'm closing this issue.
