### ISSUE TITLE
Basic Redux

### ISSUE THREAD

**Issue by marduke182** [BarcelonaJS/speakers#8]
---
level: beginner
language: es
twitter: @marduke182
tags:
  - Redux

---

Me and a friend @jvlucic are looking to give some talks in the BCNJS meetups if you are interested. Specifically it would be two talks ( we are not sure if both should be in the same session or separate ), one would be for teaching basic Redux and the second for more advanced Redux #9:

This would be this gist of it (pending changes):

**The Basic of Redux:**

- An introduction to reducers.
- Managing the state as an inmutable data.
- The benefits of an unique state tree.
- Dispatching actions and modifying the state.
- Time travel / Testing
- Introduction to middlewares and store enhancers

I hope you find this interesting!

**Comment by PatrickHeneise** [comment]
Very! Since it's 2 talks and we're trying to get the semantics for all talks right, could you change this issue to include the first session only and create a second issue for the 2nd talk please?

When can you give the talks?

**Comment by marduke182** [comment]
Done!

The march meetup sounds good?

**Comment by PatrickHeneise** [comment]
Sounds good!

**Comment by PatrickHeneise** [comment]
Thanks!

**Comment by xpujol** [comment]
I'd love it if this was the March BarcelonaJS talk.

**Comment by karlas** [comment]
I would be very interested too!

**Comment by Elecash** [comment]
:+1:

**Comment by tomas2387** [comment]
:+1:

**Comment by danielart** [comment]
I'm very interested to assist this Basic Redux talk

**Comment by aralroca** [comment]
I will be there! Sounds good

**Comment by nevillegallimore** [comment]
This sounds very promising!

**Comment by PatrickHeneise** [comment]
@marduke182 can we schedule this talk for March?

**Comment by marduke182** [comment]
Yes, perfect.

**Comment by PatrickHeneise** [comment]
Great. I have to fix something in gitevents, then I'll assign it to March.
