### ISSUE TITLE
An advance introduction to Redux

### ISSUE THREAD

**Issue by marduke182** [BarcelonaJS/speakers#9]
---
level: advanced
language: en
twitter: @jvlucic
tags:
  - Redux Thunk
  - Redux Promise
  - Redux Saga
  - Redux Loop

---

Continue the talk proposal of #8 

**An advance introduction to Redux:**

- Explain thunk and promise middleware.
- Managing side effects data flows with this middleware
- Introduction to sagas and the benefits over thunk and promise middlewares
- A brief example using redux-loop instead saga.
- Using Reselect and Normalizr for performance
- Framework Agnostic real life examples (A little Twitch Client over React, AngularJS and React Native with the same Redux logic, maybe Ember @jsangilve is helping me here)

**Comment by karlas** [comment]
Interested!

**Comment by xpujol** [comment]
+1

**Comment by danielart** [comment]
+1

**Comment by giuband** [comment]
+1

**Comment by jsangilve** [comment]
+1

**Comment by dfvalero** [comment]
:+1:

**Comment by vermiculite** [comment]
+1

**Comment by PatrickHeneise** [comment]
Should we schedule this talk for April?

**Comment by marduke182** [comment]
Yes

**Comment by PatrickHeneise** [comment]
Perfect

**Comment by jvlucic** [comment]
Hi! I will be giving this talk, so yes! April sounds good! once you set a specific date please let me know. Also, can I do it in english?

**Comment by PatrickHeneise** [comment]
Date ist Apr 13, english is preferred :)

**Comment by marduke182** [comment]
Perfect, I updated the language and added some extra information in the description.

**Comment by Vistur** [comment]
+1

**Comment by PatrickHeneise** [comment]
@marduke182 booked!

**Comment by marduke182** [comment]
@PatrickHeneise Thanks. The performer is @jvlucic. I will make a pull request this afternoon here: 
https://github.com/BarcelonaJS/BarcelonaJS/blob/master/talks/20160413-an-advance-introduction-to-redux.md

**Comment by PatrickHeneise** [comment]
Yeah, `gitevents` is pulling the author from the github author. Either PR or re-submit from him. Thanks
